services:
  - type: web
    name: voting-system-web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        sync: false

      - key: DB_PORT
        value: "3306"

      - key: DB_NAME
        sync: false

      - key: DB_USER
        sync: false

      - key: DB_PASS
        sync: false

      - key: ADMIN_USER
        value: admin

      - key: ADMIN_PASS
        generateValue: true

      - key: ADMIN_EMAIL
        value: admin@voting.local